"""empty message

Revision ID: 93e126a28d22
Revises: 3d9b36f476dd
Create Date: 2021-05-15 17:36:49.094587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e126a28d22'
down_revision = '3d9b36f476dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'password_hash')
    # ### end Alembic commands ###
