"""empty message

Revision ID: b1f4835dfda5
Revises: adca3e17369a
Create Date: 2021-05-22 23:03:24.700560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1f4835dfda5'
down_revision = 'adca3e17369a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_view', sa.Column('article_id', sa.Integer(), nullable=True))
    op.drop_constraint('article_view_ibfk_1', 'article_view', type_='foreignkey')
    op.create_foreign_key(None, 'article_view', 'article', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_column('article_view', 'article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_view', sa.Column('article', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'article_view', type_='foreignkey')
    op.create_foreign_key('article_view_ibfk_1', 'article_view', 'article', ['article'], ['id'], ondelete='CASCADE')
    op.drop_column('article_view', 'article_id')
    # ### end Alembic commands ###
